#ifndef TYPES_H
#define TYPES_H

#include <iostream>

enum class TYPES {
    FIRE, WATER, GRASS, ELECTRIC, ICE, FIGHTING,
    POISON, GROUND, FLYING, PSYCHIC, BUG, ROCK,
    GHOST, DARK, DRAGON, STEEL, FAIRY, NORMAL, NONE
};

#endif
